name: codelessly_starter
description: "{{description}}"

publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  codelessly_sdk: ^1.8.0

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/codelessly_config.json
